# Copyright 2026 Limx Dynamics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""ARM RA-BC / AW-BC sample weighters.

Official implementation of https://arxiv.org/abs/2604.03037
"""

from __future__ import annotations
import logging
from pathlib import Path
from typing import Any, Dict, Mapping

import numpy as np
import pyarrow.parquet as pq
import torch

from fluxvla.engines import WEIGHTERS
from .utils import resolve_rabc_progress_path, resolve_sample_index


@WEIGHTERS.register_module()
class ArmRABCWeighter:
    """Compute RA-BC weights from ARM progress values.

    Official implementation of https://arxiv.org/abs/2604.03037

    The progress parquet is generated by
    ``scripts/compute_arm_awbc_progress.py`` and contains global frame indices
    plus a scalar ``progress`` column. For each sample, RA-BC uses:

    ``delta = progress[t + chunk_size] - progress[t]``
    """

    progress_column = 'progress'

    def __init__(self,
                 progress_path: str | Path,
                 chunk_size: int,
                 kappa: float = 0.01,
                 epsilon: float = 1e-6,
                 fallback_weight: float = 1.0,
                 index_key: str = 'index',
                 device: torch.device | str | None = None) -> None:
        if chunk_size < 1:
            raise ValueError(f'chunk_size must be >= 1, got {chunk_size}')

        self.progress_path = resolve_rabc_progress_path(progress_path)
        self.chunk_size = chunk_size
        self.kappa = kappa
        self.epsilon = epsilon
        self.fallback_weight = fallback_weight
        self.index_key = index_key
        self.device = torch.device(device) if device is not None else (
            torch.device('cuda')
            if torch.cuda.is_available() else torch.device('cpu'))

        logging.info('Loading ARM RA-BC progress from %s', self.progress_path)
        table = pq.read_table(self.progress_path)
        data = table.to_pydict()
        if self.progress_column not in data:
            available = [
                key for key in data.keys() if key.startswith('progress')
            ]
            raise ValueError(
                f'Column {self.progress_column!r} missing from '
                f'{self.progress_path}. Available progress columns: '
                f'{available}')

        self.progress_lookup: Dict[int, float] = {}
        self.episode_lookup: Dict[int, tuple[int, int]] = {}
        self.episode_boundaries: Dict[tuple[int, int], Dict[str, int]] = {}
        self.explicit_episode_lengths: Dict[tuple[int, int], int] = {}
        self._load_progress_rows(data)
        self._compute_global_stats()

    def _load_progress_rows(self, data: Dict[str, list]) -> None:
        indices = data['index']
        episode_indices = data['episode_index']
        dataset_indices = data.get('dataset_index',
                                   [0 for _ in range(len(indices))])
        progress_values = data[self.progress_column]
        episode_lengths = data.get('episode_length')

        for row_idx, (idx, dataset_idx, episode_idx, progress) in enumerate(
                zip(indices, dataset_indices, episode_indices,
                    progress_values)):
            global_idx = int(idx)
            episode_key = (int(dataset_idx), int(episode_idx))
            self.episode_lookup[global_idx] = episode_key

            if progress is not None and np.isfinite(progress):
                self.progress_lookup[global_idx] = float(progress)

            if episode_lengths is not None:
                episode_length = episode_lengths[row_idx]
                if episode_length is not None and np.isfinite(episode_length):
                    self.explicit_episode_lengths[episode_key] = int(
                        episode_length)

            bounds = self.episode_boundaries.setdefault(
                episode_key, {
                    'start': global_idx,
                    'end': global_idx + 1
                })
            bounds['start'] = min(bounds['start'], global_idx)
            bounds['end'] = max(bounds['end'], global_idx + 1)

        logging.info('Loaded %d ARM progress rows for RA-BC',
                     len(self.progress_lookup))

    def _compute_global_stats(self) -> None:
        deltas = []
        for global_idx, progress in self.progress_lookup.items():
            future_progress = self._future_progress(global_idx)
            if future_progress is not None:
                deltas.append(future_progress - progress)

        if not deltas:
            self.delta_mean = 0.0
            self.delta_std = self.epsilon
            logging.warning('No valid ARM RA-BC progress deltas found')
            return

        self.delta_mean = max(float(np.mean(deltas)), 0.0)
        self.delta_std = max(float(np.std(deltas)), self.epsilon)
        logging.info('ARM RA-BC delta stats: mean=%.4f std=%.4f',
                     self.delta_mean, self.delta_std)

    def _future_progress(self, global_idx: int) -> float | None:
        episode_key = self.episode_lookup.get(global_idx)
        if episode_key is None:
            return None
        bounds = self.episode_boundaries.get(episode_key)
        if bounds is None:
            return None
        future_idx = min(global_idx + self.chunk_size, bounds['end'] - 1)
        return self.progress_lookup.get(future_idx)

    def compute_batch_weights(
            self, batch: Dict[str,
                              Any]) -> tuple[torch.Tensor, Dict[str, Any]]:
        indices = batch.get('index', batch.get('current_index'))
        if indices is None:
            batch_size = self._get_batch_size(batch)
            return torch.ones(
                batch_size, device=self.device), {
                    'mean_weight': 1.0,
                    'num_zero_weight': 0,
                    'num_full_weight': batch_size,
                }

        if isinstance(indices, torch.Tensor):
            indices = indices.detach().cpu().numpy().tolist()
        elif isinstance(indices, np.ndarray):
            indices = indices.tolist()

        deltas = np.asarray([self._compute_delta(int(idx)) for idx in indices],
                            dtype=np.float32)
        weights = self._compute_weights(deltas)
        stats = {
            'mean_weight': float(np.nanmean(weights)),
            'num_zero_weight': int(np.sum(weights == 0.0)),
            'num_full_weight': int(np.sum(weights == 1.0)),
        }

        weight_tensor = torch.as_tensor(
            weights, device=self.device, dtype=torch.float32)
        weight_sum = weight_tensor.sum() + self.epsilon
        weight_tensor = weight_tensor * len(weight_tensor) / weight_sum
        return weight_tensor, stats

    def compute_weight(self, index: int) -> float:
        delta = self._compute_delta(int(index))
        weights = self._compute_weights(np.asarray([delta], dtype=np.float32))
        return float(weights[0])

    def __call__(self, sample: Mapping[str, Any]) -> float:
        index = resolve_sample_index(sample, self.index_key)
        if index is None:
            return self.fallback_weight
        return self.compute_weight(index)

    def _compute_delta(self, global_idx: int) -> float:
        progress = self.progress_lookup.get(global_idx)
        if progress is None:
            return float('nan')
        future_progress = self._future_progress(global_idx)
        if future_progress is None:
            return float('nan')
        return future_progress - progress

    def _compute_weights(self, deltas: np.ndarray) -> np.ndarray:
        valid_mask = ~np.isnan(deltas)
        lower_bound = self.delta_mean - 2 * self.delta_std
        soft_weights = (deltas - lower_bound) / (4 * self.delta_std +
                                                 self.epsilon)
        soft_weights = np.clip(soft_weights, 0.0, 1.0)

        weights = np.zeros_like(deltas, dtype=np.float32)
        weights[deltas > self.kappa] = 1.0
        moderate_mask = (deltas >= 0.0) & (deltas <= self.kappa)
        weights[moderate_mask] = soft_weights[moderate_mask]
        weights[~valid_mask] = self.fallback_weight
        return weights

    def _get_batch_size(self, batch: Dict[str, Any]) -> int:
        for key in ['action', 'actions', 'index', 'current_index']:
            value = batch.get(key)
            if isinstance(value, (torch.Tensor, np.ndarray)):
                return int(value.shape[0])
        return 1

    def get_stats(self) -> Dict[str, Any]:
        return {
            'type': 'arm_rabc',
            'num_frames': len(self.progress_lookup),
            'chunk_size': self.chunk_size,
            'delta_mean': self.delta_mean,
            'delta_std': self.delta_std,
            'kappa': self.kappa,
        }


@WEIGHTERS.register_module()
class ArmAWBCWeighter(ArmRABCWeighter):
    """Compute AW-BC weights from ARM progress plus episode-length scaling.

    Official implementation of https://arxiv.org/abs/2604.03037

    AW-BC applies RA-BC progress-delta weighting, then multiplies each sample
    by:

    ``duration_weight = episode_length / mean_episode_length``
    """

    def __init__(self,
                 progress_path: str | Path,
                 chunk_size: int,
                 kappa: float = 0.01,
                 epsilon: float = 1e-6,
                 fallback_weight: float = 1.0,
                 index_key: str = 'index',
                 device: torch.device | str | None = None) -> None:
        super().__init__(
            progress_path=progress_path,
            chunk_size=chunk_size,
            kappa=kappa,
            epsilon=epsilon,
            fallback_weight=fallback_weight,
            index_key=index_key,
            device=device,
        )
        self._init_episode_length_stats()

    def _init_episode_length_stats(self) -> None:
        """Derive episode lengths and mean duration from progress parquet."""
        self.episode_lengths: Dict[tuple[int, int],
                                   int] = dict(self.explicit_episode_lengths)

        for episode_key, bounds in self.episode_boundaries.items():
            if episode_key not in self.episode_lengths:
                self.episode_lengths[episode_key] = (
                    bounds['end'] - bounds['start'])

        if self.episode_lengths:
            self.mean_episode_length = max(
                float(np.mean(list(self.episode_lengths.values()))),
                self.epsilon,
            )
        else:
            self.mean_episode_length = self.epsilon
            logging.warning('No episode lengths found for AW-BC; using 1.0 '
                            'duration scaling.')

        logging.info(
            'AW-BC episode length stats: mean=%.2f episodes=%d',
            self.mean_episode_length,
            len(self.episode_lengths),
        )

    def _duration_weight(self, global_idx: int) -> float:
        episode_key = self.episode_lookup.get(global_idx)
        if episode_key is None:
            return 1.0
        episode_length = self.episode_lengths.get(episode_key,
                                                  self.mean_episode_length)
        return float(episode_length) / self.mean_episode_length

    def compute_batch_weights(
            self, batch: Dict[str,
                              Any]) -> tuple[torch.Tensor, Dict[str, Any]]:
        indices = batch.get('index', batch.get('current_index'))
        if indices is None:
            batch_size = self._get_batch_size(batch)
            return torch.ones(
                batch_size, device=self.device), {
                    'mean_weight': 1.0,
                    'mean_duration_weight': 1.0,
                    'num_zero_weight': 0,
                    'num_full_weight': batch_size,
                }

        if isinstance(indices, torch.Tensor):
            indices = indices.detach().cpu().numpy().tolist()
        elif isinstance(indices, np.ndarray):
            indices = indices.tolist()

        deltas = np.asarray([self._compute_delta(int(idx)) for idx in indices],
                            dtype=np.float32)
        weights = self._compute_weights(deltas)
        duration_weights = np.asarray(
            [self._duration_weight(int(idx)) for idx in indices],
            dtype=np.float32,
        )
        weights = weights * duration_weights
        stats = {
            'mean_weight': float(np.nanmean(weights)),
            'mean_duration_weight': float(np.nanmean(duration_weights)),
            'num_zero_weight': int(np.sum(weights == 0.0)),
            'num_full_weight':
            int(np.sum(np.isclose(weights, duration_weights))),
        }

        weight_tensor = torch.as_tensor(
            weights, device=self.device, dtype=torch.float32)
        weight_sum = weight_tensor.sum() + self.epsilon
        weight_tensor = weight_tensor * len(weight_tensor) / weight_sum
        return weight_tensor, stats

    def compute_weight(self, index: int) -> float:
        delta = self._compute_delta(int(index))
        weights = self._compute_weights(np.asarray([delta], dtype=np.float32))
        duration_weight = self._duration_weight(int(index))
        return float(weights[0] * duration_weight)

    def get_stats(self) -> Dict[str, Any]:
        stats = super().get_stats()
        stats.update({
            'type': 'awbc',
            'mean_episode_length': self.mean_episode_length,
            'num_episodes': len(self.episode_lengths),
        })
        return stats
