# Copyright 2026 Limx Dynamics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""SARM RA-BC sample weighters."""

from __future__ import annotations
import logging
from pathlib import Path
from typing import Any, Dict, Mapping

import numpy as np
import pyarrow.parquet as pq
import torch

from fluxvla.engines import WEIGHTERS
from .utils import resolve_rabc_progress_path, resolve_sample_index


@WEIGHTERS.register_module()
class SarmRABCWeighter:
    """Compute RA-BC weights from SARM progress parquet values.

    The progress parquet is generated by
    ``scripts/compute_sarm_rabc_progress.py`` and contains global frame
    indices plus ``progress_sparse`` and/or ``progress_dense`` columns. For
    each sample, RA-BC uses:

    ``delta = progress[t + chunk_size] - progress[t]``
    """

    def __init__(self,
                 progress_path: str | Path,
                 chunk_size: int,
                 head_mode: str = 'sparse',
                 kappa: float = 0.01,
                 epsilon: float = 1e-6,
                 fallback_weight: float = 1.0,
                 index_key: str = 'index',
                 device: torch.device | str | None = None) -> None:
        if chunk_size < 1:
            raise ValueError(f'chunk_size must be >= 1, got {chunk_size}')
        if head_mode not in ['sparse', 'dense']:
            raise ValueError(
                f"head_mode must be 'sparse' or 'dense', got {head_mode!r}")

        self.progress_path = resolve_rabc_progress_path(progress_path)
        self.chunk_size = chunk_size
        self.head_mode = head_mode
        self.kappa = kappa
        self.epsilon = epsilon
        self.fallback_weight = fallback_weight
        self.index_key = index_key
        self.device = torch.device(device) if device is not None else (
            torch.device('cuda')
            if torch.cuda.is_available() else torch.device('cpu'))
        self.progress_column = f'progress_{head_mode}'

        logging.info('Loading SARM RA-BC progress from %s', self.progress_path)
        table = pq.read_table(self.progress_path)
        data = table.to_pydict()
        if self.progress_column not in data:
            available = [
                key for key in data.keys() if key.startswith('progress_')
            ]
            raise ValueError(
                f'Column {self.progress_column!r} missing from '
                f'{self.progress_path}. Available progress columns: '
                f'{available}')

        self.progress_lookup: Dict[int, float] = {}
        self.episode_lookup: Dict[int, tuple[int, int]] = {}
        self.episode_boundaries: Dict[tuple[int, int], Dict[str, int]] = {}
        self._load_progress_rows(data)
        self._compute_global_stats()

    def _load_progress_rows(self, data: Dict[str, list]) -> None:
        indices = data['index']
        episode_indices = data['episode_index']
        dataset_indices = data.get('dataset_index',
                                   [0 for _ in range(len(indices))])
        progress_values = data[self.progress_column]

        for idx, dataset_idx, episode_idx, progress in zip(
                indices, dataset_indices, episode_indices, progress_values):
            global_idx = int(idx)
            episode_key = (int(dataset_idx), int(episode_idx))
            self.episode_lookup[global_idx] = episode_key

            if progress is not None and np.isfinite(progress):
                self.progress_lookup[global_idx] = float(progress)

            bounds = self.episode_boundaries.setdefault(
                episode_key, {
                    'start': global_idx,
                    'end': global_idx + 1
                })
            bounds['start'] = min(bounds['start'], global_idx)
            bounds['end'] = max(bounds['end'], global_idx + 1)

        logging.info('Loaded %d SARM progress rows for RA-BC',
                     len(self.progress_lookup))

    def _compute_global_stats(self) -> None:
        deltas = []
        for global_idx, progress in self.progress_lookup.items():
            future_progress = self._future_progress(global_idx)
            if future_progress is not None:
                deltas.append(future_progress - progress)

        if not deltas:
            self.delta_mean = 0.0
            self.delta_std = self.epsilon
            logging.warning('No valid RA-BC progress deltas found')
            return

        self.delta_mean = max(float(np.mean(deltas)), 0.0)
        self.delta_std = max(float(np.std(deltas)), self.epsilon)
        logging.info('RA-BC delta stats: mean=%.4f std=%.4f', self.delta_mean,
                     self.delta_std)

    def _future_progress(self, global_idx: int) -> float | None:
        episode_key = self.episode_lookup.get(global_idx)
        if episode_key is None:
            return None
        bounds = self.episode_boundaries.get(episode_key)
        if bounds is None:
            return None
        future_idx = min(global_idx + self.chunk_size, bounds['end'] - 1)
        return self.progress_lookup.get(future_idx)

    def compute_batch_weights(
            self, batch: Dict[str,
                              Any]) -> tuple[torch.Tensor, Dict[str, Any]]:
        indices = batch.get('index', batch.get('current_index'))
        if indices is None:
            batch_size = self._get_batch_size(batch)
            return torch.ones(
                batch_size, device=self.device), {
                    'mean_weight': 1.0,
                    'num_zero_weight': 0,
                    'num_full_weight': batch_size,
                }

        if isinstance(indices, torch.Tensor):
            indices = indices.detach().cpu().numpy().tolist()
        elif isinstance(indices, np.ndarray):
            indices = indices.tolist()

        deltas = np.asarray([self._compute_delta(int(idx)) for idx in indices],
                            dtype=np.float32)
        weights = self._compute_weights(deltas)
        stats = {
            'mean_weight': float(np.nanmean(weights)),
            'num_zero_weight': int(np.sum(weights == 0.0)),
            'num_full_weight': int(np.sum(weights == 1.0)),
        }

        weight_tensor = torch.as_tensor(
            weights, device=self.device, dtype=torch.float32)
        weight_sum = weight_tensor.sum() + self.epsilon
        weight_tensor = weight_tensor * len(weight_tensor) / weight_sum
        return weight_tensor, stats

    def compute_weight(self, index: int) -> float:
        delta = self._compute_delta(int(index))
        weights = self._compute_weights(np.asarray([delta], dtype=np.float32))
        return float(weights[0])

    def __call__(self, sample: Mapping[str, Any]) -> float:
        index = resolve_sample_index(sample, self.index_key)
        if index is None:
            return self.fallback_weight
        return self.compute_weight(index)

    def _compute_delta(self, global_idx: int) -> float:
        progress = self.progress_lookup.get(global_idx)
        if progress is None:
            return float('nan')
        future_progress = self._future_progress(global_idx)
        if future_progress is None:
            return float('nan')
        return future_progress - progress

    def _compute_weights(self, deltas: np.ndarray) -> np.ndarray:
        valid_mask = ~np.isnan(deltas)
        lower_bound = self.delta_mean - 2 * self.delta_std
        soft_weights = (deltas - lower_bound) / (4 * self.delta_std +
                                                 self.epsilon)
        soft_weights = np.clip(soft_weights, 0.0, 1.0)

        weights = np.zeros_like(deltas, dtype=np.float32)
        weights[deltas > self.kappa] = 1.0
        moderate_mask = (deltas >= 0.0) & (deltas <= self.kappa)
        weights[moderate_mask] = soft_weights[moderate_mask]
        weights[~valid_mask] = self.fallback_weight
        return weights

    def _get_batch_size(self, batch: Dict[str, Any]) -> int:
        for key in ['action', 'actions', 'index', 'current_index']:
            value = batch.get(key)
            if isinstance(value, (torch.Tensor, np.ndarray)):
                return int(value.shape[0])
        return 1

    def get_stats(self) -> Dict[str, Any]:
        return {
            'type': 'rabc',
            'num_frames': len(self.progress_lookup),
            'chunk_size': self.chunk_size,
            'head_mode': self.head_mode,
            'delta_mean': self.delta_mean,
            'delta_std': self.delta_std,
            'kappa': self.kappa,
        }
